In [1]:
import numpy as np
import r1cs, witness

OUT = np.array(r1cs.OUT)
A= np.array(r1cs.L)
B= np.array(r1cs.R)

w = np.array(witness.w)

print(OUT.dot(w))
print(A.dot(w))
print(B.dot(w))
print(np.multiply(A.dot(w), B.dot(w)))

result = OUT.dot(w) == np.multiply(A.dot(w), B.dot(w))

print(result.all())


[ 49 343  14]
[ 7 49  7]
[7 7 2]
[ 49 343  14]
True
